import type { MundialData } from "@/types";

export const mundialData: MundialData = {
  torneo: {
    nombre: "Copa Mundial de la FIFA 2026",
    edicion: 23,
    formato: "48 selecciones / 104 partidos",
    fecha_inicio: "2026-06-11",
    fecha_final: "2026-07-19",
    sedes: ["Estados Unidos", "México", "Canadá"],
    partido_inaugural:
      "México vs. Sudáfrica — Estadio Azteca, Ciudad de México",
    partido_final: "MetLife Stadium, East Rutherford, Nueva Jersey",
  },
  canales_por_pais: {
    Chile: {
      nota: "Chilevisión tiene los derechos exclusivos de televisión abierta. Transmitirá ~52 partidos, incluyendo inauguración, semifinales y final. DSports (DirecTV) transmite los 104 partidos.",
      television_abierta: [
        {
          canal: "Chilevisión (CHV)",
          tipo: "abierta",
          partidos:
            "~52 partidos seleccionados (inauguración, semifinales, final y partidos destacados)",
          streaming_gratuito: "MiCHV (app) y Chilevision.cl",
          resolucion:
            "HD / 4K HDR en señal especial via ClaroVTR (canal 557) y VTR (canal 710)",
        },
      ],
      television_pago: [
        {
          canal: "DSports (DirecTV Sports)",
          tipo: "cable/satélite",
          partidos: "104 partidos (cobertura completa)",
          plataforma_streaming: "DGO (app y web)",
        },
        {
          canal: "Disney+ Premium (ESPN)",
          tipo: "streaming de pago",
          partidos:
            "~30 partidos seleccionados (fase de grupos, 16avos, octavos, cuartos, semis y final)",
        },
        {
          canal: "Claro TV (canal 557)",
          tipo: "cable",
          partidos: "Señal 4K HDR del Mundial via alianza con Chilevisión",
          nota: "Sin costo adicional para suscriptores con equipamiento compatible",
        },
        {
          canal: "VTR (canal 710)",
          tipo: "cable",
          partidos: "Señal 4K HDR del Mundial via alianza con Chilevisión",
          nota: "Requiere dispositivo dbox smart; sin costo adicional para suscriptores",
        },
      ],
      youtube: [
        {
          canal: "Chilevisión YouTube",
          url: "https://www.youtube.com/@chilevision",
          contenido:
            "Resúmenes, highlights y contenido complementario. La FIFA también acordó con YouTube la posibilidad de transmitir los primeros 10 minutos de todos los partidos en determinados mercados (disponibilidad en Chile aún por confirmar).",
          nota: "No hay transmisión EN VIVO confirmada de partidos completos por YouTube en Chile",
        },
      ],
    },
    Brasil: {
      nota: "Brasil tiene la cobertura más amplia de Latinoamérica. CazéTV transmitirá todos los 104 partidos de forma gratuita en YouTube. TV Globo emitirá 52 partidos incluyendo todos los de Brasil y la final.",
      television_abierta: [
        {
          canal: "TV Globo",
          tipo: "abierta",
          partidos:
            "52 partidos, incluyendo todos los partidos de Brasil, la final y partidos seleccionados",
          resolucion: "HD (sin 4K en señal abierta)",
          nota: "Primera vez que Globo no tiene todos los partidos del Mundial",
        },
        {
          canal: "SBT (Sistema Brasileiro de Televisão)",
          tipo: "abierta",
          partidos:
            "Partidos seleccionados (derechos parciales en alianza con N Sports)",
          nota: "Acuerdo anunciado en septiembre de 2025",
        },
      ],
      television_pago: [
        {
          canal: "SporTV (Grupo Globo)",
          tipo: "cable — canal deportivo",
          partidos: "55 partidos en calidad 4K via plataforma OTT Globoplay",
          plataforma_streaming: "Globoplay (app y web)",
        },
        {
          canal: "GE TV (Globo)",
          tipo: "streaming",
          partidos: "Partidos transmitidos por el Grupo Globo",
          nota: "Disponible online, sin resolución 4K",
        },
        {
          canal: "N Sports (NSports)",
          tipo: "cable",
          partidos: "Partidos seleccionados en alianza con SBT",
          nota: "Canal deportivo de pago",
        },
      ],
      youtube: [
        {
          canal: "CazéTV",
          url: "https://www.youtube.com/@CazeTV",
          tipo: "YouTube — GRATUITO",
          partidos: "104 partidos EN VIVO (cobertura completa del torneo)",
          resolucion:
            "4K (primera transmisión 4K gratuita del Mundial en YouTube)",
          conductor: "Casimiro Miguel (streamer)",
          productora: "LiveMode",
          nota: "Récord histórico en Qatar 2022: 6 millones de dispositivos simultáneos. Para Brasil únicamente.",
          derechos: "Derechos exclusivos para territorio brasileño",
        },
      ],
    },
  },
  fixture: {
    fase_grupos: [
      {
        jornada: 1,
        fecha: "2026-06-11",
        dia: "Jueves",
        partidos: [
          {
            numero: 1,
            partido: "México vs. Sudáfrica",
            grupo: "A",
            hora_chile: "15:00",
            hora_brasil: "16:00",
            sede: "Estadio Azteca, Ciudad de México",
            nota: "Partido inaugural",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO", "Disney+"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },
            canales_brasil: {
              abierta: ["TV Globo", "SBT"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 2,
            partido: "Corea del Sur vs. República Checa",
            grupo: "A",
            hora_chile: "22:00",
            hora_brasil: "23:00",
            sede: "Estadio Akron, Guadalajara",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO", "Disney+"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },
            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
        ],
      },
      {
        jornada: 1,
        fecha: "2026-06-12",
        dia: "Viernes",
        partidos: [
          {
            numero: 3,
            partido: "Canadá vs. Bosnia y Herzegovina",
            grupo: "B",
            hora_chile: "15:00",
            hora_brasil: "16:00",
            sede: "BMO Field, Toronto",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },
            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 4,
            partido: "Estados Unidos vs. Paraguay",
            grupo: "D",
            hora_chile: "21:00",
            hora_brasil: "22:00",
            sede: "SoFi Stadium, Inglewood (Los Ángeles)",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO", "Disney+"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },
            canales_brasil: {
              abierta: ["TV Globo", "SBT"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
        ],
      },
      {
        jornada: 1,
        fecha: "2026-06-13",
        dia: "Sábado",
        partidos: [
          {
            numero: 5,
            partido: "Qatar vs. Suiza",
            grupo: "B",
            hora_chile: "15:00",
            hora_brasil: "16:00",
            sede: "Levi's Stadium, Santa Clara (San Francisco)",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },
            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 6,
            partido: "Brasil vs. Marruecos",
            grupo: "C",
            hora_chile: "18:00",
            hora_brasil: "19:00",
            sede: "MetLife Stadium, East Rutherford (Nueva Jersey)",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO", "Disney+"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },
            canales_brasil: {
              abierta: ["TV Globo", "SBT"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 7,
            partido: "Haití vs. Escocia",
            grupo: "C",
            hora_chile: "21:00",
            hora_brasil: "22:00",
            sede: "Gillette Stadium, Foxborough (Boston)",
            canales_chile: {
              abierta: [],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: [],
            },
            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 8,
            partido: "Australia vs. Turquía",
            grupo: "D",
            hora_chile: "00:00 (+1 día)",
            hora_brasil: "01:00 (+1 día)",
            sede: "BC Place, Vancouver",
            canales_chile: {
              abierta: [],
              pago: ["DSports/DirecTV", "DGO", "Disney+"],
              youtube: [],
            },
            canales_brasil: {
              abierta: ["TV Globo"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
        ],
      },
      {
        jornada: 1,
        fecha: "2026-06-14",
        dia: "Domingo",
        partidos: [
          {
            numero: 9,
            partido: "Alemania vs. Curazao",
            grupo: "E",
            hora_chile: "13:00",
            hora_brasil: "14:00",
            sede: "NRG Stadium, Houston",
            canales_brasil: {
              abierta: ["TV Globo","SBT"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 10,
            partido: "Países Bajos vs. Japón",
            grupo: "F",
            hora_chile: "16:00",
            hora_brasil: "17:00",
            sede: "AT&T Stadium, Dallas",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: ["TV Globo","SBT"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 11,
            partido: "Costa de Marfil vs. Ecuador",
            grupo: "E",
            hora_chile: "19:00",
            hora_brasil: "20:00",
            sede: "Lincoln Financial Field, Philadelphia",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: ["TV Globo"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 12,
            partido: "Suecia vs. Túnez",
            grupo: "F",
            hora_chile: "22:00",
            hora_brasil: "23:00",
            sede: "Estadio BBVA, Monterrey",
            canales_brasil: {
              abierta: ["TV Globo"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
        ],
      },
      {
        jornada: 1,
        fecha: "2026-06-15",
        dia: "Lunes",
        partidos: [
          {
            numero: 13,
            partido: "España vs. Cabo Verde",
            grupo: "H",
            hora_chile: "12:00",
            hora_brasil: "13:00",
            sede: "Mercedes-Benz Stadium, Atlanta",
            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 14,
            partido: "Bélgica vs. Egipto",
            grupo: "G",
            hora_chile: "15:00",
            hora_brasil: "16:00",
            sede: "Lumen Field, Seattle",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: ["TV Globo"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 15,
            partido: "Arabia Saudita vs. Uruguay",
            grupo: "H",
            hora_chile: "18:00",
            hora_brasil: "19:00",
            sede: "Hard Rock Stadium, Miami",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: ["TV Globo","SBT"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 16,
            partido: "Irán vs. Nueva Zelanda",
            grupo: "G",
            hora_chile: "21:00",
            hora_brasil: "22:00",
            sede: "SoFi Stadium, Los Ángeles",
            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
        ],
      },
      {
        jornada: 1,
        fecha: "2026-06-16",
        dia: "Martes",
        partidos: [
          {
            numero: 17,
            partido: "Francia vs. Senegal",
            grupo: "I",
            hora_chile: "15:00",
            hora_brasil: "16:00",
            sede: "MetLife Stadium, Nueva Jersey",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: ["TV Globo","SBT"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 18,
            partido: "Irak vs. Noruega",
            grupo: "I",
            hora_chile: "18:00",
            hora_brasil: "19:00",
            sede: "Gillette Stadium, Boston",
            canales_brasil: {
              abierta: ["TV Globo"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 19,
            partido: "Argentina vs. Argelia",
            grupo: "J",
            hora_chile: "21:00",
            hora_brasil: "22:00",
            sede: "Arrowhead Stadium, Kansas City",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: ["TV Globo","SBT"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 20,
            partido: "Austria vs. Jordania",
            grupo: "J",
            hora_chile: "00:00 (+1 día)",
            hora_brasil: "01:00 (+1 día)",
            sede: "Levi's Stadium, San Francisco",
            canales_brasil: {
              abierta: ["TV Globo"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
        ],
      },
      {
        jornada: 1,
        fecha: "2026-06-17",
        dia: "Miércoles",
        partidos: [
          {
            numero: 21,
            partido: "Portugal vs. RD de Congo",
            grupo: "K",
            hora_chile: "13:00",
            hora_brasil: "14:00",
            sede: "NRG Stadium, Houston",
            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 22,
            partido: "Inglaterra vs. Croacia",
            grupo: "L",
            hora_chile: "16:00",
            hora_brasil: "17:00",
            sede: "AT&T Stadium, Dallas",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: ["TV Globo","SBT"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 23,
            partido: "Ghana vs. Panamá",
            grupo: "L",
            hora_chile: "19:00",
            hora_brasil: "20:00",
            sede: "BMO Field, Toronto",
            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 24,
            partido: "Uzbekistán vs. Colombia",
            grupo: "K",
            hora_chile: "22:00",
            hora_brasil: "23:00",
            sede: "Estadio Azteca, Ciudad de México",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: ["TV Globo"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
        ],
      },
      {
        jornada: 2,
        fecha: "2026-06-18",
        dia: "Jueves",
        partidos: [
          {
            numero: 25,
            partido: "República Checa vs. Sudáfrica",
            grupo: "A",
            hora_chile: "12:00",
            hora_brasil: "13:00",
            sede: "Mercedes-Benz Stadium, Atlanta",
            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 26,
            partido: "Suiza vs. Bosnia y Herzegovina",
            grupo: "B",
            hora_chile: "15:00",
            hora_brasil: "16:00",
            sede: "SoFi Stadium, Los Ángeles",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 27,
            partido: "Canadá vs. Qatar",
            grupo: "B",
            hora_chile: "18:00",
            hora_brasil: "19:00",
            sede: "BC Place, Vancouver",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 28,
            partido: "México vs. Corea del Sur",
            grupo: "A",
            hora_chile: "21:00",
            hora_brasil: "22:00",
            sede: "Estadio Akron, Guadalajara",
            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
        ],
      },
      {
        jornada: 2,
        fecha: "2026-06-19",
        dia: "Viernes",
        partidos: [
          {
            numero: 29,
            partido: "Estados Unidos vs. Australia",
            grupo: "D",
            hora_chile: "15:00",
            hora_brasil: "16:00",
            sede: "Lumen Field, Seattle",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 30,
            partido: "Escocia vs. Marruecos",
            grupo: "C",
            hora_chile: "18:00",
            hora_brasil: "19:00",
            sede: "Gillette Stadium, Boston",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 31,
            partido: "Brasil vs. Haití",
            grupo: "C",
            hora_chile: "20:30",
            hora_brasil: "21:30",
            sede: "Lincoln Financial Field, Philadelphia",
            nota: "Partido de Brasil",
            canales_brasil_destacados: {
              abierta: ["TV Globo"],
              youtube: ["CazéTV (en vivo, 4K)"],
            },
          },
          {
            numero: 32,
            partido: "Turquía vs. Paraguay",
            grupo: "D",
            hora_chile: "23:00",
            hora_brasil: "00:00 (+1 día)",
            sede: "Levi's Stadium, San Francisco",
            canales_brasil: {
              abierta: ["TV Globo"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
        ],
      },
      {
        jornada: 2,
        fecha: "2026-06-20",
        dia: "Sábado",
        partidos: [
          {
            numero: 33,
            partido: "Países Bajos vs. Suecia",
            grupo: "F",
            hora_chile: "13:00",
            hora_brasil: "14:00",
            sede: "NRG Stadium, Houston",
            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 34,
            partido: "Alemania vs. Costa de Marfil",
            grupo: "E",
            hora_chile: "16:00",
            hora_brasil: "17:00",
            sede: "BMO Field, Toronto",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 35,
            partido: "Ecuador vs. Curazao",
            grupo: "E",
            hora_chile: "22:00",
            hora_brasil: "23:00",
            sede: "Arrowhead Stadium, Kansas City",
            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 36,
            partido: "Túnez vs. Japón",
            grupo: "F",
            hora_chile: "00:00 (+1 día)",
            hora_brasil: "01:00 (+1 día)",
            sede: "Estadio BBVA, Monterrey",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: ["TV Globo"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
        ],
      },
      {
        jornada: 2,
        fecha: "2026-06-21",
        dia: "Domingo",
        partidos: [
          {
            numero: 37,
            partido: "España vs. Arabia Saudita",
            grupo: "H",
            hora_chile: "12:00",
            hora_brasil: "13:00",
            sede: "Mercedes-Benz Stadium, Atlanta",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 38,
            partido: "Bélgica vs. Irán",
            grupo: "G",
            hora_chile: "15:00",
            hora_brasil: "16:00",
            sede: "SoFi Stadium, Los Ángeles",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 39,
            partido: "Uruguay vs. Cabo Verde",
            grupo: "H",
            hora_chile: "18:00",
            hora_brasil: "19:00",
            sede: "Hard Rock Stadium, Miami",
            canales_brasil: {
              abierta: ["TV Globo","SBT"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 40,
            partido: "Nueva Zelanda vs. Egipto",
            grupo: "G",
            hora_chile: "21:00",
            hora_brasil: "22:00",
            sede: "BC Place, Vancouver",
            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
        ],
      },
      {
        jornada: 2,
        fecha: "2026-06-22",
        dia: "Lunes",
        partidos: [
          {
            numero: 41,
            partido: "Argentina vs. Austria",
            grupo: "J",
            hora_chile: "13:00",
            hora_brasil: "14:00",
            sede: "AT&T Stadium, Dallas",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: ["TV Globo","SBT"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 42,
            partido: "Francia vs. Irak",
            grupo: "I",
            hora_chile: "17:00",
            hora_brasil: "18:00",
            sede: "Lincoln Financial Field, Philadelphia",
            canales_brasil: {
              abierta: ["TV Globo"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 43,
            partido: "Noruega vs. Senegal",
            grupo: "I",
            hora_chile: "20:00",
            hora_brasil: "21:00",
            sede: "MetLife Stadium, Nueva Jersey",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 44,
            partido: "Jordania vs. Argelia",
            grupo: "J",
            hora_chile: "23:00",
            hora_brasil: "00:00 (+1 día)",
            sede: "Levi's Stadium, San Francisco",
            canales_brasil: {
              abierta: ["TV Globo"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
        ],
      },
      {
        jornada: 2,
        fecha: "2026-06-23",
        dia: "Martes",
        partidos: [
          {
            numero: 45,
            partido: "Portugal vs. Uzbekistán",
            grupo: "K",
            hora_chile: "13:00",
            hora_brasil: "14:00",
            sede: "NRG Stadium, Houston",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 46,
            partido: "Inglaterra vs. Ghana",
            grupo: "L",
            hora_chile: "16:00",
            hora_brasil: "17:00",
            sede: "Gillette Stadium, Boston",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: ["TV Globo","SBT"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 47,
            partido: "Panamá vs. Croacia",
            grupo: "L",
            hora_chile: "19:00",
            hora_brasil: "20:00",
            sede: "BMO Field, Toronto",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 48,
            partido: "Colombia vs. RD de Congo",
            grupo: "K",
            hora_chile: "22:00",
            hora_brasil: "23:00",
            sede: "Estadio Akron, Guadalajara",
            canales_brasil: {
              abierta: ["TV Globo"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
        ],
      },
      {
        jornada: 3,
        fecha: "2026-06-24",
        dia: "Miércoles",
        nota: "Últimos partidos de los grupos B y C (simultáneos dentro de cada grupo)",
        partidos: [
          {
            numero: 49,
            partido: "Suiza vs. Canadá",
            grupo: "B",
            hora_chile: "15:00",
            hora_brasil: "16:00",
            sede: "BC Place, Vancouver",
            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 50,
            partido: "Bosnia y Herzegovina vs. Qatar",
            grupo: "B",
            hora_chile: "15:00",
            hora_brasil: "16:00",
            sede: "Levi's Stadium, San Francisco",
            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 51,
            partido: "Marruecos vs. Haití",
            grupo: "C",
            hora_chile: "20:00",
            hora_brasil: "21:00",
            sede: "NRG Stadium, Houston",
            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 52,
            partido: "Brasil vs. Escocia",
            grupo: "C",
            hora_chile: "20:00",
            hora_brasil: "21:00",
            sede: "MetLife Stadium, Nueva Jersey",
            nota: "Partido de Brasil",
            canales_brasil_destacados: {
              abierta: ["TV Globo"],
              youtube: ["CazéTV (en vivo, 4K)"],
            },
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },
          },
        ],
      },
      {
        jornada: 3,
        fecha: "2026-06-25",
        dia: "Jueves",
        nota: "Últimos partidos de los grupos A y D (simultáneos dentro de cada grupo)",
        partidos: [
          {
            numero: 53,
            partido: "México vs. República Checa",
            grupo: "A",
            hora_chile: "15:00",
            hora_brasil: "16:00",
            sede: "Estadio Azteca, Ciudad de México",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: ["TV Globo"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 54,
            partido: "Sudáfrica vs. Corea del Sur",
            grupo: "A",
            hora_chile: "15:00",
            hora_brasil: "16:00",
            sede: "Estadio Akron, Guadalajara",
            canales_brasil: {
              abierta: ["TV Globo"],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 55,
            partido: "Paraguay vs. Australia",
            grupo: "D",
            hora_chile: "20:00",
            hora_brasil: "21:00",
            sede: "AT&T Stadium, Dallas",
            canales_chile: {
              abierta: ["Chilevisión"],
              pago: ["DSports/DirecTV", "DGO"],
              youtube: ["Chilevisión YouTube (resumen)"],
            },            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
          {
            numero: 56,
            partido: "Turquía vs. Estados Unidos",
            grupo: "D",
            hora_chile: "20:00",
            hora_brasil: "21:00",
            sede: "Lumen Field, Seattle",
            canales_brasil: {
              abierta: [],
              pago: ["SporTV", "N Sports"],
              youtube: ["CazéTV (en vivo)"],
            },
          },
        ],
      },
      {
        nota: "Los grupos E–L se completan entre el 26 y 30 de junio siguiendo el mismo esquema: jornada 3 con partidos simultáneos dentro de cada grupo. Los horarios siguen el mismo patrón (una franja a las 15:00 Chile y otra a las 20:00 Chile). Todos los partidos disponibles en DSports/DGO para Chile y CazéTV (YouTube) para Brasil.",
      },
    ],
    fase_eliminatoria: {
      segunda_fase: {
        fecha_inicio: "2026-07-01",
        fecha_fin: "2026-07-05",
        total_partidos: 16,
        nota: "32 equipos clasificados: 1°, 2° de cada grupo y 8 mejores terceros",
        canales_chile: {
          abierta: ["Chilevisión (partidos seleccionados)"],
          pago: ["DSports/DirecTV", "DGO", "Disney+"],
          youtube: ["Chilevisión YouTube (resúmenes)"],
        },
        canales_brasil: {
          abierta: [],
          pago: ["SporTV", "N Sports"],
          youtube: ["CazéTV (en vivo)"],
        },
      },
      octavos_de_final: {
        fecha_inicio: "2026-07-07",
        fecha_fin: "2026-07-10",
        total_partidos: 8,
        canales_chile: {
          abierta: ["Chilevisión"],
          pago: ["DSports/DirecTV", "DGO", "Disney+"],
          youtube: ["Chilevisión YouTube (resúmenes)"],
        },
        canales_brasil: {
          abierta: ["TV Globo", "SBT"],
          pago: ["SporTV", "Globoplay (4K)", "N Sports"],
          youtube: ["CazéTV (en vivo, todos los partidos)"],
        },
      },
      cuartos_de_final: {
        fecha_inicio: "2026-07-11",
        fecha_fin: "2026-07-12",
        total_partidos: 4,
        canales_chile: {
          abierta: ["Chilevisión"],
          pago: ["DSports/DirecTV", "DGO", "Disney+"],
          youtube: ["Chilevisión YouTube (resúmenes)"],
        },
        canales_brasil: {
          abierta: ["TV Globo"],
          pago: ["SporTV", "Globoplay (4K)", "N Sports"],
          youtube: ["CazéTV (en vivo, 4K)"],
        },
      },
      semifinales: {
        fecha: "2026-07-14 y 2026-07-15",
        total_partidos: 2,
        sedes: ["Mercedes-Benz Stadium, Atlanta", "AT&T Stadium, Dallas"],
        canales_chile: {
          abierta: ["Chilevisión"],
          pago: ["DSports/DirecTV", "DGO", "Disney+"],
          youtube: ["Chilevisión YouTube (resúmenes)"],
        },
        canales_brasil: {
          abierta: ["TV Globo"],
          pago: ["SporTV", "Globoplay (4K)"],
          youtube: ["CazéTV (en vivo, 4K)"],
        },
      },
      tercer_puesto: {
        fecha: "2026-07-18",
        sede: "Hard Rock Stadium, Miami",
        canales_chile: {
          abierta: ["Chilevisión"],
          pago: ["DSports/DirecTV", "DGO"],
          youtube: [],
        },
        canales_brasil: {
          abierta: ["TV Globo"],
          pago: ["SporTV"],
          youtube: ["CazéTV (en vivo)"],
        },
      },
      final: {
        fecha: "2026-07-19",
        hora_chile: "16:00 (aprox.)",
        hora_brasil: "17:00 (aprox.)",
        sede: "MetLife Stadium, East Rutherford, Nueva Jersey",
        canales_chile: {
          abierta: ["Chilevisión"],
          pago: ["DSports/DirecTV", "DGO", "Disney+"],
          youtube: ["Chilevisión YouTube (resúmenes post-partido)"],
        },
        canales_brasil: {
          abierta: ["TV Globo", "SBT"],
          pago: ["SporTV", "Globoplay (4K)", "N Sports"],
          youtube: ["CazéTV (en vivo, 4K)"],
        },
      },
    },
  },
  resumen_canales: {
    Chile: {
      television_abierta: {
        "Chilevisión (CHV)":
          "~52 partidos seleccionados. Canal oficial exclusivo de TV abierta. Streaming gratuito: MiCHV y chilevision.cl",
      },
      television_pago: {
        "DSports / DirecTV Sports": "104 partidos — cobertura completa",
        DGO: "Plataforma digital de DirecTV — 104 partidos online",
        "Disney+ Premium (ESPN)": "~30 partidos seleccionados",
        "Claro TV (canal 557)":
          "Señal 4K HDR (via acuerdo con Chilevisión)",
        "VTR (canal 710)":
          "Señal 4K HDR (via acuerdo con Chilevisión, requiere dbox smart)",
      },
      youtube_streaming_gratuito: {
        "Chilevisión YouTube":
          "Resúmenes, highlights y contenido complementario. No transmisión EN VIVO confirmada de partidos completos.",
        "FIFA+ / YouTube FIFA":
          "Acuerdo FIFA-YouTube: primeros 10 min de todos los partidos disponibles en mercados seleccionados (Chile pendiente de confirmación)",
      },
    },
    Brasil: {
      television_abierta: {
        "TV Globo":
          "52 partidos: todos los de Brasil, la final y partidos seleccionados. Sin 4K en señal abierta.",
        SBT: "Partidos seleccionados (derechos parciales en alianza con N Sports)",
      },
      television_pago: {
        "SporTV (Grupo Globo)":
          "Partidos del Grupo Globo con 55 encuentros en 4K via Globoplay",
        Globoplay: "Plataforma OTT del Grupo Globo — 4K para partidos de Globo/SporTV",
        "GE TV": "Streaming del Grupo Globo (sin 4K)",
        "N Sports": "Partidos seleccionados en alianza con SBT",
      },
      youtube_streaming_gratuito: {
        CazéTV:
          "104 partidos EN VIVO y GRATIS en YouTube. Resolución 4K. Canal: youtube.com/@CazeTV. Solo disponible para territorio brasileño. Fundado por Casimiro Miguel / LiveMode.",
      },
    },
  },
  fuentes: [
    "ESPN Deportes — fixture oficial FIFA 2026",
    "El Mostrador — canales TV Chile (publicado 29/05/2026)",
    "Redgol.cl — Chilevisión 52 partidos",
    "Chilevisión.cl — calendario oficial CHV (publicado 05/06/2026)",
    "tvenserio.com — alianza ClaroVTR + Chilevisión 4K",
    "Goal.com — canales Brasil 2026",
    "Calendário do Mundial 2026 (PDF Globo/CazéTV/SBT) — canales Brasil",
    "ElComercio.pe — CazéTV 104 partidos YouTube Brasil",
    "Sopitas.com — CazéTV YouTube Brasil",
    "AlAireLibre.cl — YouTube FIFA acuerdo Chile",
  ],
  notas_generales: [
    "Los horarios están en hora local de Chile (UTC-4) y Brasil (UTC-3, Brasilia).",
    "Chile NO clasificó al Mundial 2026.",
    "Brasil está en el Grupo C junto a Marruecos, Haití y Escocia.",
    "La asignación exacta de partidos a Chilevisión en señal abierta para fases eliminatorias puede variar; se confirman ~52 en total.",
    "CazéTV opera únicamente para Brasil. No está disponible en Chile ni otros países.",
    "Disney+ transmite solo 30 partidos en Chile; no cubre todos los encuentros.",
    "El fixture de los grupos E al L sigue el mismo esquema horario que los grupos A-D.",
    "Horarios sujetos a confirmación oficial de FIFA para fases eliminatorias.",
  ],
};
